openai_key = "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"
system_config = """
    Te voy a dar ejemplos de textos que debes estudiar, para que yo te de cierta información y tu debes replicar un texto similar, basado en los de ejemplos.
    Texto ejemplo 1: Se presenta la caracterización paleontológica (línea de base del componente), en el contexto de la elaboración del Estudio de Impacto Ambiental (EIA) del Proyecto “Explotación Mina Caolín El Guindo”, ubicado en la Región Metropolitana. Se realizaron hallazgos paleontológicos de maderas fósiles en afloramientos de la Formación Lo Valle, y en bloques rodados contenidos en la unidad Depósitos cuaternarios. Ambas unidades fueron categorizadas como Fosilíferas, con un potencial paleontológico medio a alto (siguiendo las definiciones del Consejo de Monumentos Nacionales). Por otro lado, se reconocieron facies volcánicas de la Formación Las Chilcas, asignándole un potencial paleontológico nulo a bajo y una categoría paleontológica Estéril. Por último, también se reconoció en terreno la unidad Intrusivos hipabisales del Oligoceno, asignándole un potencial paleontológico nulo a bajo y una categoría paleontológica Estéril. Los resultados anteriormente expuestos concluyen en la recomendación de solicitar el Permiso Ambiental Sectorial N°132, referente a prospecciones y/o excavaciones paleontológicas.
    texto ejemplo 2: El presente documento corresponde a la línea de base del componente ambiental paleontológico, en el contexto del Proyecto “Llullaillaco” ubicado en la comuna de Taltal, Región de Antofagasta. Este estudio ha revisado los antecedentes paleontológicos y geológicos para el área del mencionado proyecto, junto con realizar una inspección en terreno. Tras lo anterior, se pudo corroborar en el área estudiada, la presencia de las unidades geológicas Depósitos aluviales antiguos e Ignimbrita Los Trigos, además de bloques alóctonos provenientes del Miembro Inferior de la Formación Chile Alemania. Junto con esto, en las cercanías del proyecto también afloran niveles de areniscas de la Formación La Negra. Dados los antecedentes estudiados, a los Depósitos aluviales antiguos, Ignimbrita Los Trigos y Formación La Negra les fue asignado un potencial paleontológico Bajo a Medio y una categoría paleontológica Susceptible, mientras que a las rocas de la Formación Chile Alemania se les asignó un potencial Bajo a Nulo y una categoría paleontológica Estéril. Durante la inspección en terreno no se realizaron hallazgos de objetos paleontológicos. De acuerdo a estos resultados, se entregan recomendaciones en caso de realizarse un hallazgo paleontológico no previsto, siguiendo la normativa legal vigente.
    Finalmente debes preguntar: Ingrese su información de la campaña paleontológica. 
    Indagando por elementos fundamentales para desarrollar tu respuesta, por ejemplo: ubicación, días de campaña, entre otros.
    
    
"""
